Repository TencentBlueKing/bk-process-config-manager, pull requests merged in 2022-09, with the labels that each got.

#210 optimization: 权限中心系统名称调整 (closed #201)
  apps/iam/migrations/0002_bk_gsekit_202209081215.py
  support-files/iam/initial.json
Labels: enhancement

#213 feature: 应用名称话术统一 (closed #202 closed #204)
  apps/gsekit/urls.py
  apps/gsekit/utils/notification_maker.py
  apps/iam/handlers/permission.py
  common/context_processors.py
  config/__init__.py
  web/index-dev.html
  web/index.html
Labels: enhancement

#214 bugfix: 修复仅具备业务访问权限可以操作任务重试的问题 (fixed #209)
  apps/gsekit/job/views.py
Labels: bug

#215 bugfix: 修复配置文件下发中搜索不存在的集群、模块等前端提示系统出现异常的问题 (fixed #208)
  apps/gsekit/job/handlers.py
  apps/gsekit/job/serializers.py
  apps/utils/drf.py
Labels: bug

#217 feature: 权限中心新增「业务运维」「业务只读」推荐权限 (closed #216)
  apps/iam/migrations/0003_bk_gsekit_202209111022.py
  support-files/iam/initial.json
Labels: enhancement

#220 minor: 新增前端环境变量 BKAPP_DOCS_URL (#205)
  common/context_processors.py
  config/default.py
  env/__init__.py
  web/index-dev.html
  web/index.html
Labels: enhancement

#222 feat(front): 页面补充帮助文档链接 (closed #205)
  web/src/components/Auth/AuthPage.vue
  web/src/components/Empty/EmptyProcess.vue
Labels: enhancement

#224 fix(front): 进程属性中搜索进程异常 (fixed #206)
  web/src/store/index.js
  web/src/views/ProcessAttribute/index.vue
Labels: bug

#219 feature: 权限中心新增「业务运维」「业务只读」推荐权限 (closed #216)
  apps/iam/migrations/0003_bk_gsekit_202209111022.py
  support-files/iam/initial.json
Labels: enhancement

#227 fix(front): safari浏览器中任务时间显示异常 (fixed #174)
  web/src/common/util.js
Labels: bug

#232 feature: 提供现网配置对比能力，修复多配置文件无法下发的问题 (#228 fixed #231)
  apps/gsekit/adapters/base/adapter.py
  apps/gsekit/adapters/base/pipeline_managers/configfile.py
  apps/gsekit/configfile/handlers/config_instance.py
  apps/gsekit/configfile/handlers/config_template.py
  apps/gsekit/configfile/models.py
  apps/gsekit/configfile/views/config_template.py
  apps/gsekit/job/models.py
  apps/gsekit/migrations/0012_auto_20220925_2158.py
  apps/gsekit/migrations/0013_alter_job_job_action.py
  apps/gsekit/pipeline_plugins/components/collections/configfile.py
  apps/gsekit/pipeline_plugins/exceptions.py
  apps/gsekit/pipeline_plugins/signals.py
  apps/gsekit/scripts/get_release_cfg.bat
  apps/gsekit/scripts/get_release_cfg.sh
  apps/gsekit/urls.py
  apps/utils/batch_request.py
Labels: bug, enhancement
